name: Clock In/Out

on:
  schedule:
    # Run every weekday at random times between 8:30-9:00 and 17:30-18:00
    - cron: '30-59 8 * * 1-6'  # Monday-Saturday, between 8:30 and 9:00
    - cron: '30-59 17 * * 1-6' # Monday-Saturday, between 17:30 and 18:00

jobs:
  clock_in_out:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run clock in/out script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: python clock_in_out.py
