name: Clock In and Clock Out

on:
  schedule:
    - cron: '0 3 * * *'  # 8:30 AM IST
    - cron: '30 3 * * *' # 9:00 AM IST
    - cron: '0 12 * * *' # 5:30 PM IST
    - cron: '30 12 * * *' # 6:00 PM IST
  workflow_dispatch:

jobs:
  clock_in_out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pytz

      - name: Check installed packages
        run: pip list

      - name: Run clock_in_out script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python clock_in_out.py
