name: Clock In/Out Automation

on:
  schedule:
    - cron: '0 3 * * 1-6'  # 8:30 AM IST Monday to Saturday
    - cron: '30 12 * * 1-6' # 6:00 PM IST Monday to Saturday
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install webdriver-manager

      - name: Run clock_in_out.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LEAVE: ${{ secrets.LEAVE }}
        run: python clock_in_out.py

          PASSWORD: ${{ secrets.PASSWORD }}
        run: python clock_in_out.py
