name: Clock In/Out Automation

on:
  schedule:
    - cron: '0 3 * * 1-6'  # Runs daily at 03:00 UTC (08:30 IST)
    - cron: '30 3 * * 1-6' # Runs daily at 03:30 UTC (09:00 IST)
    - cron: '0 12 * * 1-6' # Runs daily at 12:00 UTC (17:30 IST)
    - cron: '30 12 * * 1-6' # Runs daily at 12:30 UTC (18:00 IST)
  workflow_dispatch:

jobs:
  clock_in_out:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run clock in/out script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        LEAVE: ${{ secrets.LEAVE }}
      run: |
        python clock_in_out.py

          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LEAVE: ${{ secrets.LEAVE }}
        run: python clock_in_out.py
