name: Clock In/Out Automation

on:
  schedule:
    - cron: '0 3 * * 0-6'  # Runs daily at 03:00 UTC (08:30 IST)
    - cron: '30 12 * * 0-6' # Runs daily at 12:30 UTC (18:00 IST)
  workflow_dispatch:

jobs:
  clock_in_out:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Updated to v4 for Node.js 20 compatibility

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4 for Node.js 20 compatibility
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run clock in/out script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        LEAVE: ${{ secrets.LEAVE }}
      run: |
        python clock_in_out.py
